package mil.sinte.DataService.DAO;

import java.util.List;
import mil.sinte.BusinessServices.Beans.BeanGrifoDespacho;
import mil.sinte.BusinessServices.Beans.BeanMarcas;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

/**
 *
 * @author helme
 */
public interface GrifoDespachoDAO extends JpaRepository<BeanGrifoDespacho, String> {

    @Query(nativeQuery = true, value = "SELECT COMISION.CPERIODO_CODIGO AS PERIODO, "
            + "UTIL.FUN_MESES_ABREVIATURA(COMISION.CMES_CODIGO) AS MES, "
            + "UTIL.FUN_TIPO_ASIGNACION_ABREVIATUR(COMISION.NTIPO_ASIGNACION_CODIGO) AS TIPO_ASIGNACION, "
            + "UTIL.FUN_DIVISION_EJERCITO_BRIGADA(COMISION.NBRIGADA_CODIGO) AS DIVISION, "
            + "UTIL.FUN_BRIGADA_ABREVIATURA(COMISION.NBRIGADA_CODIGO) AS BRIGADA, "
            + "UTIL.FUN_DEPENDENCIA_ABREVIATURA(COMISION.NBRIGADA_CODIGO, DETALLE.NDEPENDENCIA_CODIGO) AS UNIDAD, "
            + "UTIL.FUN_TIPO_COMBUSTIBLE_ABREVIATU(DETALLE.NTIPO_COMBUSTIBLE_CODIGO) AS TIPO_COMBUSTIBLE, "
            + "NDESPACHO_COMBUSTIBLE_CANTIDAD AS CANTIDAD, "
            + "UTIL.FUN_GRIFO_NOMBRE(NGRIFO_CODIGO) AS GRIFO, "
            + "TO_CHAR(DDESPACHO_COMBUSTIBLE_FECHA,'DD/MM/YYYY HH:MM:SS AM') AS FECHA "
            + "FROM SINTE_ASIGNACION_COMISION COMISION INNER JOIN SINTE_ASIGNACION_COMISION_DETA DETALLE ON("
            + "COMISION.CPERIODO_CODIGO=DETALLE.CPERIODO_CODIGO AND "
            + "COMISION.NBRIGADA_CODIGO=DETALLE.NBRIGADA_CODIGO AND "
            + "COMISION.NTIPO_ASIGNACION_CODIGO=DETALLE.NTIPO_ASIGNACION_CODIGO AND "
            + "COMISION.NASIGNACION_COMISION_CODIGO=DETALLE.NASIGNACION_COMISION_CODIGO) "
            + "INNER JOIN SINTE_DESPACHO_COMBUSTIBLE DESPACHO ON ("
            + "COMISION.CPERIODO_CODIGO=DESPACHO.CPERIODO_CODIGO AND "
            + "COMISION.NBRIGADA_CODIGO=DESPACHO.NBRIGADA_CODIGO AND "
            + "COMISION.NTIPO_ASIGNACION_CODIGO=DESPACHO.NTIPO_ASIGNACION_CODIGO AND "
            + "COMISION.NASIGNACION_COMISION_CODIGO=DESPACHO.NASIGNACION_COMISION_CODIGO AND "
            + "DETALLE.NASIGNACION_COMISION_DETALLE=DESPACHO.NASIGNACION_COMISION_DETALLE) WHERE "
            + "UTIL.FUN_VEHICULO(DETALLE.NVEHICULO_CODIGO)=?1  "
            + "ORDER BY DDESPACHO_COMBUSTIBLE_FECHA DESC")
    List<BeanGrifoDespacho> findByPlaca(String placa);
}
